- id: '1680030941829'
  alias: Aux heat on power outage
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - binary_sensor.grid_status
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition:
  - condition: state
    entity_id: climate.kitchen
    state: heat
  - condition: state
    entity_id: binary_sensor.grid_status
    state: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  action:
  - service: climate.set_aux_heat
    data:
      aux_heat: true
    target:
      device_id: f3b75a62f1f4994fe3318e82ef70391a
  - service: notify.notify
    data:
      message: Set the Kitchen thermostat to Aux heat
  mode: single
- id: '1680033021496'
  alias: Allow heat pump east if the power is on
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.allow_heat_pump_east
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition:
  - condition: state
    entity_id: binary_sensor.generator_power_outage
    for:
      hours: 0
      minutes: 5
      seconds: 0
    state: 'off'
    enabled: false
  - condition: state
    entity_id: binary_sensor.grid_status
    state: 'on'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  action:
  - type: turn_on
    device_id: f1eb06a0cd1de63a0a89d6f1a07c0c07
    entity_id: switch.allow_heat_pump_east
    domain: switch
  - service: notify.mobile_app_pixel_6_pro
    data:
      message: 'Auto: turned allow heat pump east back on'
  mode: single
- id: '1684022238203'
  alias: Mark is in the shop
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.mark_walker
    to: Shop
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition:
  - condition: state
    entity_id: person.mark_walker
    state: Shop
    for:
      hours: 0
      minutes: 1
      seconds: 0
  action:
  - type: turn_off
    device_id: acb27efef4a773ababb34a2d84d03a26
    entity_id: switch.wv_shop_power
    domain: switch
  - service: notify.mobile_app_pixel_9_pro_xl
    data:
      message: Mark is in the shop
  mode: single
- id: '1684546297292'
  alias: Mark left the shop
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.mark_walker
    from: Shop
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - type: turn_on
    device_id: acb27efef4a773ababb34a2d84d03a26
    entity_id: switch.wv_shop_power
    domain: switch
  - service: notify.mobile_app_pixel_9_pro_xl
    data:
      message: Mark left the shop
  mode: single
