esphome:
  name: heat-pump-west

esp32:
  board: adafruit_feather_esp32_v2

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812X
    pin: GPIO0
    num_leds: 1
    name: "On-board neopixel"
    effects:
      - random:

switch:
  - platform: gpio
    pin: 5
    name: "Allow Heat Pump West"
    restore_mode: ALWAYS_OFF

#binary_sensor:
#  - platform: gpio
#    pin:
#      number: 13
#      inverted: true
#    name: "Heat Pump West Requested"

i2c:
  sda: 22
  scl: 20
  id: bus_a

bme680_bsec:
  address: 0x77

sensor:
  - platform: bme680_bsec
    temperature:
      name: "BME680 Temperature"
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    iaq:
      name: "BME680 IAQ"
      id: iaq
    co2_equivalent:
      name: "BME680 CO2 Equivalent"
    breath_voc_equivalent:
      name: "BME680 Breath VOC Equivalent"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret heat_pump_west

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Outdoor-Thermostat"
    password: !secret wifi_ap_password

captive_portal:
