esphome:
  name: "tank-chlorine"
  friendly_name: Chlorine Tank

esp32:
  board: adafruit_feather_esp32s2_tft
  framework:
    type: arduino

output:
  - platform: gpio
    pin: 7
    inverted: True
    id: tft_power

i2c:
  sda: 3
  scl: 4
  scan: False
  frequency: 100kHz

sensor:
  - platform: bme680
    address: 0x77
    temperature:
      name: "Temperature"

text_sensor:
  - platform: wifi_info
    scan_results:
      name: "WiFi Scan"
      id: wifi_scan
    ip_address:
      name: "IP Address"
      id: wifi_ip_address

spi:
  clk_pin: GPIO36
  mosi_pin: GPIO35

display:
  - platform: st7789v
    model: TTGO_TDISPLAY_135X240
    backlight_pin: GPIO45
    cs_pin: GPIO42
    dc_pin: GPIO40
    reset_pin: GPIO41
    lambda: |-
      it.print(0, 0, id(roboto), "Hello World!");

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 20

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret tank_chlorine

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Tank-Chlorine"
    password: !secret wifi_ap_password

captive_portal:
